# ========= POSTGRES =========
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/lotodb_test
spring.datasource.username=postgrestest
spring.datasource.password=postgrestest

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ========= MONGODB =========
# spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# spring.data.mongodb.uri=mongodb://localhost:27017/lotodb_test
spring.data.mongodb.uri=mongodb://mongotest:mongotest@localhost:27017/lotodb_test?authSource=lotodb_test
# spring.data.mongodb.uri=mongodb://mongotest:mongotest@localhost:27017/lotodb_test?authSource=admin

# ========= MIGRATIONS =========

# ========= MIGRATIONS =========
spring.flyway.enabled=false
spring.liquibase.enabled=false

# ========= SCHEDULERS =========
spring.task.scheduling.enabled=false

# ========= SPRING =========
spring.main.banner-mode=off
logging.level.root=WARN

# ========= SECURITY (JWT) =========
# on garde Spring Security actif !
spring.security.filter.dispatcher-types=REQUEST,ERROR
