FROM python:3.11-slim

WORKDIR /app

# deps minimales
RUN pip install --no-cache-dir fastapi uvicorn[standard] httpx pymongo

COPY ai.py /app/ai.py

EXPOSE 8091
CMD ["uvicorn", "ai:app", "--host", "0.0.0.0", "--port", "8091"]
