server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    # open-in-view: false
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Paris

  flyway:
    enabled: false   # mets true si tu utilises Flyway et que tes migrations sont prêtes

logging:
  level:
    org.hibernate.SQL: warn
